upstream/taskManager/urls.py
#     _  _                        __   __
#  __| |(_)__ _ _ _  __ _ ___   _ \ \ / /
# / _` || / _` | ' \/ _` / _ \_| ' \ V /
# \__,_|/ \__,_|_||_\__, \___(_)_||_\_/
#     |__/          |___/
#
#			INSECURE APPLICATION WARNING
#
# django.nV is a PURPOSELY INSECURE web-application
# meant to demonstrate Django security problems
# UNDER NO CIRCUMSTANCES should you take any code
# from django.nV for use in another web application!
#

from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       url(r'^$',
                           'taskManager.views.index',
                           name='index'),
                       url(r'^taskManager/',
                           include('taskManager.taskManager_urls',
                                   namespace="taskManager")),
                       url(r'^admin/',
                           include(admin.site.urls)),
                      )

upstream/taskManager/models.py
#     _  _                        __   __
#  __| |(_)__ _ _ _  __ _ ___   _ \ \ / /
# / _` || / _` | ' \/ _` / _ \_| ' \ V /
# \__,_|/ \__,_|_||_\__, \___(_)_||_\_/
#     |__/          |___/
#
#			INSECURE APPLICATION WARNING
#
# django.nV is a PURPOSELY INSECURE web-application
# meant to demonstrate Django security problems
# UNDER NO CIRCUMSTANCES should you take any code
# from django.nV for use in another web application!
#

import datetime

from django.contrib.auth.models import User

from django.utils import timezone
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    image = models.CharField(max_length=3000, default="")
    reset_token = models.CharField(max_length=7, default="")
    reset_token_expiration = models.DateTimeField(default=timezone.now)

class Project(models.Model):
    title = models.CharField(max_length=50, default='Default')
    text = models.CharField(max_length=500)
    start_date = models.DateTimeField('date started')
    due_date = models.DateTimeField(
        'date due',
        default=(
            timezone.now() +
            datetime.timedelta(
                weeks=1)))
    users_assigned = models.ManyToManyField(User)
    priority = models.IntegerField(default=1)

    def __str__(self):
        return self.title

    def was_created_recently(self):
        return self.start_date >= timezone.now() - datetime.timedelta(days=1)

    def is_overdue(self):
        return self.due_date <= timezone.now()

    def percent_complete(self):
        counter = 0
        for task in self.task_set.all():
            counter = counter + (1 if task.completed else 0)
        try:
            return round(float(counter) / self.task_set.count() * 100)
        except ZeroDivisionError:
            return 0


class Task(models.Model):
    project = models.ForeignKey(Project, default=1)
    text = models.CharField(max_length=200)
    title = models.CharField(max_length=200, default="N/A")
    start_date = models.DateTimeField('date created')
    due_date = models.DateTimeField(
        'date due',
        default=(
            timezone.now() +
            datetime.timedelta(
                weeks=1)))
    completed = models.NullBooleanField(default=False)
    users_assigned = models.ManyToManyField(User)

    def __str__(self):
        return self.text

    def was_created_recently(self):
        return self.start_date >= timezone.now() - datetime.timedelta(days=1)

    def is_overdue(self):
        return self.due_date <= timezone.now()

    def percent_complete(self):
        return 100 if self.completed else 0


class Notes(models.Model):
    task = models.ForeignKey(Task, default=1)
    title = models.CharField(max_length=200, default="N/A")
    text = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    user = models.CharField(max_length=200, default='ancestor')

    def __str__(self):
        return self.text


class File(models.Model):
    project = models.ForeignKey(Project)
    name = models.CharField(max_length=300, default="")
    path = models.CharField(max_length=3000, default="")

    def __str__(self):
        return self.name

upstream/taskManager/forms.py
#     _  _                        __   __
#  __| |(_)__ _ _ _  __ _ ___   _ \ \ / /
# / _` || / _` | ' \/ _` / _ \_| ' \ V /
# \__,_|/ \__,_|_||_\__, \___(_)_||_\_/
#     |__/          |___/
#
#           INSECURE APPLICATION WARNING
#
# django.nV is a PURPOSELY INSECURE web-application
# meant to demonstrate Django security problems
# UNDER NO CIRCUMSTANCES should you take any code
# from django.nV for use in another web application!
#

""" forms.py contains various Django forms for the application """

from taskManager.models import Project, Task
from django import forms
from django.contrib.auth.models import User


def get_my_choices_users():
    """ Retrieves a list of all users in the system
        for the user management page
    """

    user_list = User.objects.order_by('date_joined')
    user_tuple = []
    counter = 1
    for user in user_list:
        user_tuple.append((counter, user))
        counter = counter + 1
    return user_tuple


def get_my_choices_tasks(current_proj):
    """ Retrieves all tasks in the system
        for the task management page
    """

    task_list = []
    tasks = Task.objects.all()
    for task in tasks:
        if task.project == current_proj:
            task_list.append(task)

    task_tuple = []
    counter = 1
    for task in task_list:
        task_tuple.append((counter, task))
        counter = counter + 1
    return task_tuple


def get_my_choices_projects():
    """ Retrieves all projects in the system
        for the project management page
    """

    proj_list = Project.objects.all()
    proj_tuple = []
    counter = 1
    for proj in proj_list:
        proj_tuple.append((counter, proj))
        counter = counter + 1
    return proj_tuple

# A2: Broken Authentication and Session Management


class UserForm(forms.ModelForm):
    """ User registration form """
    class Meta:
        model = User
        exclude = ['groups', 'user_permissions', 'last_login', 'date_joined', 'is_active']


class ProjectFileForm(forms.Form):
    """ Used for uploading files attached to projects """
    name = forms.CharField(max_length=300)
    file = forms.FileField()


class ProfileForm(forms.Form):
    """ Provides a form for editing your own profile """
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.CharField(max_length=300, required=False)
    picture = forms.FileField(required=False)

upstream/taskManager/views.py
#     _  _                        __   __
#  __| |(_)__ _ _ _  __ _ ___   _ \ \ / /
# / _` || / _` | ' \/ _` / _ \_| ' \ V /
# \__,_|/ \__,_|_||_\__, \___(_)_||_\_/
#     |__/          |___/
#
#			INSECURE APPLICATION WARNING
#
# django.nV is a PURPOSELY INSECURE web-application
# meant to demonstrate Django security problems
# UNDER NO CIRCUMSTANCES should you take any code
# from django.nV for use in another web application!
#

import datetime
import mimetypes
import os
import codecs

from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponse
from django.utils import timezone
from django.template import RequestContext
from django.db import connection

from django.views.decorators.csrf import csrf_exempt

from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth.models import Group, User
from django.contrib.auth import logout

from taskManager.models import Task, Project, Notes, File, UserProfile
from taskManager.misc import store_uploaded_file
from taskManager.forms import UserForm, ProjectFileForm, ProfileForm


def manage_tasks(request, project_id):

    user = request.user
    proj = Project.objects.get(pk=project_id)

    if user.is_authenticated():

        if user.has_perm('can_change_task'):

            if request.method == 'POST':

                userid = request.POST.get("userid")
                taskid = request.POST.get("taskid")

                user = User.objects.get(pk=userid)
                task = Task.objects.get(pk=taskid)

                task.users_assigned.add(user)

                return redirect('/taskManager/')
            else:
                return render_to_response(
                    'taskManager/manage_tasks.html',
                    {
                        'tasks': Task.objects.filter(
                            project=proj).order_by('title'),
                        'users': User.objects.order_by('date_joined')},
                    RequestContext(request))

        else:
            return redirect('/taskManager/', {'permission': False})

    return redirect('/taskManager/', {'logged_in': False})


def manage_projects(request):

    user = request.user

    if user.is_authenticated():
        logged_in = True

        if user.has_perm('can_change_group'):

            if request.method == 'POST':

                userid = request.POST.get("userid")
                projectid = request.POST.get("projectid")

                user = User.objects.get(pk=userid)
                project = Project.objects.get(pk=projectid)

                project.users_assigned.add(user)

                return redirect('/taskManager/')
            else:

                return render_to_response(
                    'taskManager/manage_projects.html',
                    {
                        'projects': Project.objects.order_by('title'),
                        'users': User.objects.order_by('date_joined'),
                        'logged_in': logged_in},
                    RequestContext(request))

        else:
            return redirect('/taskManager/', {'permission': False})

    return redirect('/taskManager/', {'logged_in': False})

# A7 - Missing Function Level Access Control


def manage_groups(request):

    user = request.user

    if user.is_authenticated():

        user_list = User.objects.order_by('date_joined')

        if request.method == 'POST':

            post_data = request.POST.dict()

            accesslevel = post_data["accesslevel"].strip()

            if accesslevel in ['admin_g', 'project_managers', 'team_member']:

                # Create the group if it doesn't already exist
                try:
                    grp = Group.objects.get(name=accesslevel)
                except Group.DoesNotExist:
                    grp = Group.objects.create(name=accesslevel)
                specified_user = User.objects.get(pk=post_data["userid"])
                # Check if the user even exists
                if specified_user is None:
                    return redirect('/taskManager/', {'permission': False})
                specified_user.groups.add(grp)
                specified_user.save()
                return render_to_response(
                    'taskManager/manage_groups.html',
                    {
                        'users': user_list,
                        'groups_changed': True,
                        'logged_in': True},
                    RequestContext(request))
            else:
                return render_to_response(
                    'taskManager/manage_groups.html',
                    {
                        'users': user_list,
                        'logged_in': True},
                    RequestContext(request))

        else:
            if user.has_perm('can_change_group'):
                return render_to_response(
                    'taskManager/manage_groups.html',
                    {
                        'users': user_list,
                        'logged_in': True},
                    RequestContext(request))
            else:
                return redirect('/taskManager/', {'permission': False})

    return redirect('/taskManager/', {'logged_in': False})

# A4: Insecure Direct Object Reference (IDOR)


def upload(request, project_id):

    if request.method == 'POST':

        proj = Project.objects.get(pk=project_id)
        form = ProjectFileForm(request.POST, request.FILES)

        if form.is_valid():
            name = request.POST.get('name', False)
            upload_path = store_uploaded_file(name, request.FILES['file'])

            #A1 - Injection (SQLi)
            curs = connection.cursor()
            curs.execute(
                "insert into taskManager_file ('name','path','project_id') values ('%s','%s',%s)" %
                (name, upload_path, project_id))

            # file = File(
            #name = name,
            #path = upload_path,
            # project = proj)

            # file.save()

            return redirect('/taskManager/' + project_id +
                            '/', {'new_file_added': True})
        else:
            form = ProjectFileForm()
    else:
        form = ProjectFileForm()
    return render_to_response(
        'taskManager/upload.html', {'form': form}, RequestContext(request))

# A4: Insecure Direct Object Reference (IDOR)


def download(request, file_id):

    file = File.objects.get(pk=file_id)
    abspath = open(
        os.path.dirname(
            os.path.realpath(__file__)) +
        file.path,
        'rb')
    response = HttpResponse(content=abspath.read())
    response['Content-Type'] = mimetypes.guess_type(file.path)[0]
    response['Content-Disposition'] = 'attachment; filename=%s' % file.name
    return response


def download_profile_pic(request, user_id):

    user = User.objects.get(pk=user_id)
    filepath = user.userprofile.image
    if len(filepath) > 1:
        return redirect(filepath)
    else:
        return redirect('/static/taskManager/uploads/default.png')
    #filename = user.get_full_name()+"."+filepath.split(".")[-1]
    # try:
    #	abspath = open(filepath, 'rb')
    # except:
    #	abspath = open("./taskmanager"+filepath, 'rb')
    #response = HttpResponse(content=abspath.read())
    #response['Content-Type']= mimetypes.guess_type(filepath)[0]
    # return response

# A4: Insecure Direct Object Reference (IDOR)


def task_create(request, project_id):

    if request.method == 'POST':

        proj = Project.objects.get(pk=project_id)

        text = request.POST.get('text', False)
        task_title = request.POST.get('task_title', False)
        now = timezone.now()
        task_duedate = timezone.now() + datetime.timedelta(weeks=1)
        if request.POST.get('task_duedate') != '':
            task_duedate = datetime.datetime.fromtimestamp(
                int(request.POST.get('task_duedate', False)))

        task = Task(
            text=text,
            title=task_title,
            start_date=now,
            due_date=task_duedate,
            project=proj)

        task.save()
        task.users_assigned = [request.user]

        return redirect('/taskManager/' + project_id +
                        '/', {'new_task_added': True})
    else:
        return render_to_response(
            'taskManager/task_create.html', {'proj_id': project_id}, RequestContext(request))

# A4: Insecure Direct Object Reference (IDOR)


def task_edit(request, project_id, task_id):

    proj = Project.objects.get(pk=project_id)
    task = Task.objects.get(pk=task_id)

    if request.method == 'POST':

        if task.project == proj:

            text = request.POST.get('text', False)
            task_title = request.POST.get('task_title', False)
            task_completed = request.POST.get('task_completed', False)

            task.title = task_title
            task.text = text
            task.completed = True if task_completed == "1" else False
            task.save()

        return redirect('/taskManager/' + project_id + '/' + task_id)
    else:
        return render_to_response(
            'taskManager/task_edit.html', {'task': task}, RequestContext(request))

# A4: Insecure Direct Object Reference (IDOR)


def task_delete(request, project_id, task_id):
    proj = Project.objects.get(pk=project_id)
    task = Task.objects.get(pk=task_id)
    if proj is not None:
        if task is not None and task.project == proj:
            task.delete()

    return redirect('/taskManager/' + project_id + '/')

# A4: Insecure Direct Object Reference (IDOR)


def task_complete(request, project_id, task_id):
    proj = Project.objects.get(pk=project_id)
    task = Task.objects.get(pk=task_id)
    if proj is not None:
        if task is not None and task.project == proj:
            task.completed = not task.completed
            task.save()

    return redirect('/taskManager/' + project_id)

upstream/taskManager/templates/taskManager/base.html
<!DOCTYPE html>
<html>
    <head>
    <title>Task Manager</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Styles
    ================================================== -->  
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static "taskManager/css/bootstrap.css" %}"/>
    <link rel="stylesheet" href="{% static "taskManager/css/bootstrap.min.css" %}"/>
    <link rel="stylesheet" href="{% static "taskManager/css/font-awesome.css" %}"/>
    <link rel="stylesheet" href="{% static "taskManager/css/style.css" %}"/>
    
    
    <!-- Google Fonts
    ================================================== -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=PT+Sans:300,400,400italic,700" >
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Ubuntu:300,400,400italic,700" > 
    
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    </head>
<body>


<!-- Navbar
================================================== -->
  <header class="header-frontend">
      <div class="navbar navbar-default navbar-static-top">
          <div class="container">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                      <span class="fa fa-bars"></span>
                  </button>
                  <a class="navbar-brand" href="/">Task<span>Manager</span></a>
              </div>
              <div class="navbar-collapse collapse ">
                  <ul class="nav navbar-nav">
                      <li><a href="{% url 'taskManager:tutorials' %}">Tutorials</a></li>
                      {% if user.is_authenticated %}
                      <li><a href="/taskManager/logout">Logout</a></li>
                      {% else %}
                      <li class="active" ><a href="/taskManager/register">Sign Up</a></li>
                      <li><a href="/taskManager/login">Login</a></li>
                      {% endif %}
                  </ul>
              </div>
          </div>
      </div>
  </header>
  <!--header end-->


<!-- Body/content
================================================== -->
         <!--container start-->
          <div class="container">
              <div class="row">
                {% block content %}
                {% endblock %}
              </div>
          </div>      

<!-- Body/content -->

<!-- Footer
================================================== -->

<!--footer start-->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-sm-2">
                <h1>contact info</h1>
                <address>
                    <p>63877 Walnut Street
                    Plainstown City, VA</p>

                    <p>p: (607)456-7890</p>
                    <p>f: (607)456-7891</p>
                    <p>e: <a href="javascript:;">info@tm.com</a></p>
                </address>
            </div>
            
            <div class="col-lg-2 col-sm-2 col-lg-offset-1">
                <h1>Our Mission</h1>
                <p>Making life easier, one task at a time.</p>
            </div>
            
        </div>
    </div>
</footer>
<!--footer end-->

<!-- End Footer -->

<!-- Javascript
================================================== -->
    <!--<script src="{% static "taskManager/js/bootstrap.min.js" %}" ></script>
    <script src="http://code.jquery.com/jquery-latest.js"></script>-->
    
</body>     
</html>

upstream/taskManager/templates/taskManager/change_password.html
{% extends 'taskManager/base_backend.html' %}

{% block content   %}

<!--main content start-->
<section class="wrapper">
<div class="row">
  <div class="col-lg-6">
      <section class="panel">
          {% include 'taskManager/messages.html'%}
          <header class="panel-heading">
              Change Password
          </header>
          <div class="panel-body">
              <form method="post" role="form">
                  <div class="form-group col-lg-7 col-sm-7">
                      <label >Old Password</label>
                      <input type="password" name="old_password" class="form-control">
                      <label >New Password</label>
                      <input type="password" name="new_password" class="form-control">
                      <label >New Password (Confirm)</label>
                      <input type="password" name="confirm_password" class="form-control">
                      <hr>
                      <button type="submit" class="btn btn-info">Save</button>
                  </div>

              </form>

          </div>
      </section>
  </div>
  
</div>  
</section>

{% endblock %}

upstream/taskManager/templates/taskManager/index.html
{% extends 'taskManager/base.html' %}
 {% load staticfiles %}
 <link rel="stylesheet" href="{% static "taskManager/css/settings.css" %}"/>



{% block content %}

{% if not user.is_authenticated %}
 <div class="container">
      <div class="row">
          <!--feature start-->
          <div class="text-center feature-head">

				<p><img src="{% static "taskManager/img/logo_lg.png" %}"/></p>
				<h1>welcome to TaskManager</h1>
				<p>Purposely Insecure Professional Project Management Software</p>
          </div>
          <div class="col-lg-4 col-sm-4">
              <section>
                  <div class="f-box">
                      <i class=" fa fa-desktop"></i>
                      <h2>Powerful Design</h2>
                  </div>
                  <p class="f-text">Simplicity in design but powerful project management tracking capabilities.</p>
              </section>
          </div>
          <div class="col-lg-4 col-sm-4">
              <section>
                  <div class="f-box active">
                      <i class=" fa fa-code"></i>
                      <h2>API</h2>
                  </div>
                  <p class="f-text">Extensible interface for API driven activities, Coming soon!</p>
              </section>
          </div>
          <div class="col-lg-4 col-sm-4">
              <section>
                  <div class="f-box">
                      <i class="fa fa-gears"></i>
                      <h2>fully customizable</h2>
                  </div>
                  <p class="f-text">Customizable project management interface that allows you to manage your projects, your way.</p>
              </section>
          </div>
          <!--feature end-->
      </div>
      <div class="row">
          <!--quote start-->
          <div class="quote">
              <div class="col-lg-3 col-sm-3 text-center pull-right">
                  <a href="/taskManager/register" class="btn btn-danger purchase-btn">Sign-Up Now!</a>
              </div>
          </div>
          <!--quote end-->
      </div>
  </div>


{% endif %}

{% endblock %}

upstream/taskManager/templates/taskManager/register.html
{% extends 'taskManager/base.html' %}
      
        {% block content %}
        {% if registered %}
            <p><strong>Thanks for registering!</strong></p>
            <p><a href="/taskManager/login">Return to the homepage.</a></p>
        {% else %}
        
          <div class="col-lg-7 col-sm-7 address">
               <h4>Registration</h4>
               <div class="contact-form">
                   <form method="post" role="form" action="/taskManager/register/" enctype="multipart/form-data">
                      {% csrf_token %}
                     <div class="form-group">
                      <!-- {{ user_form }} -->
                        <tr>
                           <th><label for="id_username">Username:</label></th>
                           <td><input class="form-control" id="id_username" name="username" type="text" /></td>
                        </tr>
                        <tr>
                           <th><label for="id_first_name">First name:</label></th>
                           <td><input class="form-control" id="id_first_name" name="first_name" type="text" /></td>
                        </tr>
                        <tr>
                           <th><label for="id_last_name">Last name:</label></th>
                           <td><input class="form-control" id="id_last_name" name="last_name" type="text" /></td>
                        </tr>
                        <tr>
                           <th><label for="id_email">Email:</label></th>
                           <td><input class="form-control" id="id_email" name="email" type="text" /></td>
                        </tr>
                        <tr>
                           <th><label for="id_password">Password:</label></th>
                           <td><input class="form-control" id="id_password" name="password" type="password" /></td>
                        </tr>
                     </div>  
                       <button class="btn btn-danger" type="submit">Register</button>
                   </form>
          
               </div>
          </div>
        
        {% endif %}
        
        {%  endblock %}
      

upstream/taskManager/templates/taskManager/task_details.html
{% extends 'taskManager/base_backend.html' %}

{% block content   %}

<!--main content start-->

    <section class="wrapper site-min-height">
        <!-- page start-->
        <section class="panel col-md-10">
            <header class="panel-heading">
                <!--A3: Cross Site Scripting (XSS) -->
                {{task.title|safe}}
                <span class="pull-right">
                  <a href="{% url 'taskManager:task_edit' project_id=task.project.id task_id=task.id %}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit Task</a>
                  {% if task.completed %}
                  <a href="#" id="loading-btn" class="btn btn-success btn-xs" disabled="disabled"><i class="fa fa-check"></i> Task is Completed</a>
                  {% else %}
                  <a href="{% url 'taskManager:task_complete' project_id=task.project.id task_id=task.id %}" class="btn btn-success btn-xs"><i class="fa fa-check"></i> Complete Task</a>
                  {% endif %}
                </span>
            </header>

        </section>
        <div class="row">
            <div class="col-md-10">
                <section class="panel">
                    <div class="panel-body">
                        <div class="row p-details">
                            <div class="col-md-5">
                                <p><span class="bold">Created:</span> {{task.start_date}} </p>
                            </div>
                            <div class="col-md-5">
                                <p><span class="bold">Due:</span> {{task.due_date}} </p>
                            </div>
                            <div class="col-md-5">
                                <p><span class="bold">Participants:</span>
                                <span class="p-team">
                                    {% for u in task.users_assigned.all%}
                                      <a href="#"><img alt="image" src="{% url 'taskManager:download_profile_pic' u.id %}"></a>
                                    {% endfor %}
                                </span>
                                </p>
                            </div>
                            <div class="col-md-10">
                                <p><span class="bold">Description:</span>
                                <span class="p-team">
                                  <!--A3: Cross Site Scripting (XSS) -->
                                  {{task.text|safe}}
                                </span>
                                </p>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="panel">
                    <div class="panel-body">
                        <div class="row p-details">
                            <div class="col-md-10">
                                <span class="bold">Notes</span>
                                <span class="pull-right">
                                    <a href="{% url 'taskManager:note_create' project_id=task.project.id task_id=task.id %}" class="btn btn-primary btn-xs"> Add Note</a>
                                </span>
                            </div>
                        </div>
                        <div class="row p-details">
                            <div class="col-md-10">
                                <span class="p-team">
                                    <table class="table table-hover p-table">
                                      <thead>
                                        <tr>
                                          <th>Title</th>
                                          <th>Text</th>
                                          <th>Edit</th>
                                          <th>Del</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        {% for note in task.notes_set.all%}
                                        <tr>
                                          <td>
                                            {{note.title}}
                                          </td>
                                          <td>
                                            {{note.text}}
                                          </td>
                                          <td><a href="{% url 'taskManager:note_edit' project_id=task.project.id task_id=task.id note_id=note.id %}">Edit</a></td>
                                          <td><a href="{% url 'taskManager:note_delete' project_id=task.project.id task_id=task.id note_id=note.id %}">Delete</a></td>
                                        </tr>
                                        {% endfor %}  
                                      </tbody>
                                    </table>
                                </span>
                                </p>
                            </div>
                        </div>

                    </div>

                </section>

            </div>
        </div>
        <!-- page end-->
    </section>

{% endblock %}